// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC23GivPQE826iP06DnQvZGuafvcHwrR1A',
    appId: '1:909447691315:web:c3394e7d3473738743b746',
    messagingSenderId: '431146169809',
    projectId: 'the-hafleh-app',
    authDomain: 'the-hafleh-app.firebaseapp.com',
    storageBucket: 'the-hafleh-app.appspot.com',
    measurementId: 'G-KKL6FZWV3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3HmDAm4yCLkuzJELS26cIn4DzgQTwF8',
    appId: '1:735151566625:android:6c2f12fb82a6ce8bd65860',
    messagingSenderId: '735151566625',
    projectId: 'date-night-live',
    storageBucket: 'date-night-live.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3p0jKlucOwW_E6CMkKl5vzlgrvT6x5I',
    appId: '1:735151566625:ios:f11e1f43df73b717d65860',
    messagingSenderId: '735151566625',
    projectId: 'date-night-live',
    storageBucket: 'date-night-live.appspot.com',
    androidClientId: '',
    iosClientId:
        '735151566625-a1que6f5bb7k1b9s2ic1kb0jg5q70751.apps.googleusercontent.com',
    iosBundleId: 'com.example.DNL',
  );
}
