// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDa-kBlp-1sSDTjB6X5bAUGpbHOT5taGS4",
      authDomain: "date-night-live-2023.firebaseapp.com",
      projectId: "date-night-live-2023",
      storageBucket: "date-night-live-2023.appspot.com",
      messagingSenderId: "1025797410412",
      appId: "1:1025797410412:web:d7b8857c1c896d71721249",
      measurementId: "G-4WBBQE4FTR");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8DnT4r95TsewrW3Y21HEl9Sv99LKigPQ',
    appId: '1:1025797410412:android:dd72972a001d7f71721249',
    messagingSenderId: '1025797410412',
    projectId: 'date-night-live-2023',
    storageBucket: 'date-night-live-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxDBeI8NpnLtHGe88da2UOx5dVck5CiEg',
    appId: '1:1025797410412:ios:5c6c8c91c7ae7408721249',
    messagingSenderId: '1025797410412',
    projectId: 'date-night-live-2023',
    storageBucket: 'date-night-live-2023.appspot.com',
    androidClientId: '',
    iosClientId:
        '1025797410412-ria137uep0rmpd06hg1jhvb6ajjhn4j6.apps.googleusercontent.com',
    iosBundleId: 'com.emma.DNL',
  );
}
